// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    
		int time = Integer.parseInt(args[0]);
		double x ;
		int bigThen = 0;
		int small=0;

		 for (int i=0; i<time;i++)
		 {
			x = Math.random();
			if (x>0.5) {
				bigThen++;
			}
			else
			{
				small++;
			}
		 }
		 double ratio = bigThen/small;

		 System.out.println("> 0.5: "+bigThen);
		 System.out.println("<= 0.5: "+small);
		 System.out.println("Ratio: " +ratio);

	}
}
